/*
    batch.h - Class header file for batch class.
    Beginning Date : June 25, 2006
    Completion Date : June 25, 2006
    Latest Modification : June 25, 2006

    Code written by Sumandeep Banerjee, DFKI, Kaiserslautern, Germany
    sumandeep.banerjee@gmail.com
*/

/**
    \class Batch
    \brief Multiple file mfcc extraction

    Extracts MFCC coefficients from multiple WAVE files, and puts them into a common table
*/

#if !defined (_BATCH_H)
#define _BATCH_H

// project include files
#include "mfcc.h"

/// This temporary file is generated by the Batch class to store intermediate data
#define _BATCHTEMPFILE "batch.temp"

class Batch {
    private:
        void batchAdd (char *infile, long timeFrame);
    public:
        void batchUpdate (char **filelist, long numFiles, long timeFrame);
};

#endif
