/*
    Copyright (C) 2006-2018 Sumandeep Banerjee

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
    batch.h - Class header file for batch class.
    Beginning Date : June 25, 2006
    Completion Date : June 25, 2006
    Latest Modification : June 25, 2006

    Code written by Sumandeep Banerjee, DFKI, Kaiserslautern, Germany
    sumandeep.banerjee@gmail.com
*/

/**
    \class Batch
    \brief Multiple file mfcc extraction

    Extracts MFCC coefficients from multiple WAVE files, and puts them into a common table
*/

#if !defined (_BATCH_H)
#define _BATCH_H

// project include files
#include "mfcc.h"

/// This temporary file is generated by the Batch class to store intermediate data
#define _BATCHTEMPFILE "batch.temp"

class Batch {
    private:
        void batchAdd (char *infile, long timeFrame);
    public:
        void batchUpdate (char **filelist, long numFiles, long timeFrame);
};

#endif
